id: P006654
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159411
  title: ཕུར་ལྕོག་ངག་དབང་བྱམས་པའི་གསུང་འབུམ།
  author: ''
  volumes:
    0c2cbc71f90947e59ba3152065f711aa:
      image_group_id: I2PD18480
      title: ''
      volume_number: 1
      total_pages: 664
    566b08741f324998958e02ab9200233a:
      image_group_id: I2PD18481
      title: ''
      volume_number: 2
      total_pages: 662
    7b9ecd3e227f4315bcc05bc3cd85ba90:
      image_group_id: I2PD18482
      title: ''
      volume_number: 3
      total_pages: 654
